"""
FILE: schemas.py
PURPOSE: Data validation and serialization using Pydantic.

WHY SEPARATE MODELS (SQLAlchemy) AND SCHEMAS (Pydantic)?
1. Security: The Database Model might contain secrets (like passwords or internal IDs) 
   that you don't want to return to the user. The Schema defines exactly what the user sees.
2. Validation: Pydantic ensures the user sends the correct data types (e.g., 'title' must be a string).
   If they send a number, the API creates a nice error message automatically.
"""

from pydantic import BaseModel
from datetime import datetime

# BASE SCHEMA
# Contains fields common to both creating and reading notes.
class NoteCreate(BaseModel):
    title: str
    content: str

# RESPONSE SCHEMA
# This is what we return to the user. It includes everything in NoteCreate, 
# PLUS the fields generated by the database (id, created_at).
class NoteResponse(NoteCreate):
    id: int
    created_at: datetime

    class Config:
        # WHY from_attributes = True? (Formerly known as orm_mode)
        # Pydantic models expect a dictionary: {"title": "x", "content": "y"}
        # SQLAlchemy models are objects: note.title, note.content
        # This config tells Pydantic: "It's okay to read data from an Object, not just a Dict."
        from_attributes = True